model:
  class_path: anomalib.models.EfficientAd
  init_args:
    imagenet_dir: dataset
    teacher_out_channels: 384
    model_size: M
    lr: 0.0001
    weight_decay: 1.0e-05
    padding: false
    pad_maps: true
data:
  class_path: anomalib.data.Folder
  init_args:
    name: avatar_rigging
    root: dataset
    normal_dir: train/normal
    abnormal_dir: val
    train_batch_size: 2
    eval_batch_size: 32
    num_workers: 8
    task: segmentation
    train_transform: null
    eval_transform: null
    test_split_mode: synthetic
    test_split_ratio: 0.2
    val_split_mode: same_as_test
    val_split_ratio: 0.5
