model:
  class_path: anomalib.models.EfficientAd
  init_args:
    imagenet_dir: ./dataset/train
    teacher_out_channels: 384
    model_size: S
    lr: 0.0001
    weight_decay: 1.0e-05
    padding: false
    pad_maps: true
data:
  class_path: anomalib.data.Folder
  init_args:
    name: avatar_rigging
    root: dataset
    normal_dir: train
    abnormal_dir: anomaly
    train_batch_size: 1
    eval_batch_size: 32
    num_workers: 8
    task: classification
    train_transform: null
    eval_transform: null
    test_split_mode: synthetic
    test_split_ratio: 0.2
    val_split_mode: same_as_test
    val_split_ratio: 0.5
    image_size: [1280, 720]